Repository Pinqo-community/marketplace-app, pull requests merged in 2024-12, with the labels that each got.

#64 feat(Category): Add category section with slider, animations, and API integration
  client/package-lock.json
  client/package.json
  client/src/api/categoriesApi.tsx
  client/src/api/productsApi.tsx
  client/src/assets/icons/arrow-slider.svg
  client/src/assets/images/fruit-category.png
  client/src/components/CategoryCard/CategoryCard.module.scss
  client/src/components/CategoryCard/CategoryCard.tsx
  client/src/pages/HomePage/HomePage.module.scss
  client/src/pages/HomePage/HomePage.tsx
  client/src/store/index.ts
  client/src/types/Category.ts
Labels: Front

#50 48 crud category
  api/build.gradle
  api/gradlew
  api/src/main/java/com/marketplace/configuration/SecurityConfig.java
  api/src/main/java/com/marketplace/controller/CategoryController.java
  api/src/main/java/com/marketplace/dto/category/CategoryCreateDto.java
  api/src/main/java/com/marketplace/dto/category/CategoryResponseDto.java
  api/src/main/java/com/marketplace/dto/category/CategoryUpdateDto.java
  api/src/main/java/com/marketplace/entity/Category.java
  api/src/main/java/com/marketplace/entity/User.java
  api/src/main/java/com/marketplace/exception/AlreadyExistsException.java
  api/src/main/java/com/marketplace/exception/GlobalExceptionHandler.java
  api/src/main/java/com/marketplace/exception/NotFoundException.java
  api/src/main/java/com/marketplace/repository/CategoryRepository.java
  api/src/main/java/com/marketplace/security/jwt/CustomAccessDeniedHandler.java
  api/src/main/java/com/marketplace/service/CategoryService.java
  api/src/main/java/com/marketplace/service/impl/CategoryServiceImpl.java
  api/src/main/java/com/marketplace/utils/mapper/.gitkeep
  api/src/main/java/com/marketplace/utils/mapper/CategoryMapper.java
  api/src/main/resources/application.yml
  api/src/test/java/com/marketplace/controller/CategoryControllerTest.java
  api/src/test/java/com/marketplace/security/jwt/CustomAccessDeniedHandlerTest.java
  api/src/test/java/com/marketplace/service/impl/CategoryServiceImplTest.java
Labels: Back

#91 Fix/category cherry pick
  api/build.gradle
  api/gradlew
  api/src/main/java/com/marketplace/configuration/SecurityConfig.java
  api/src/main/java/com/marketplace/controller/CategoryController.java
  api/src/main/java/com/marketplace/dto/category/CategoryCreateDto.java
  api/src/main/java/com/marketplace/dto/category/CategoryResponseDto.java
  api/src/main/java/com/marketplace/dto/category/CategoryUpdateDto.java
  api/src/main/java/com/marketplace/entity/Category.java
  api/src/main/java/com/marketplace/entity/User.java
  api/src/main/java/com/marketplace/exception/AlreadyExistsException.java
  api/src/main/java/com/marketplace/exception/GlobalExceptionHandler.java
  api/src/main/java/com/marketplace/repository/CategoryRepository.java
  api/src/main/java/com/marketplace/security/jwt/CustomAccessDeniedHandler.java
  api/src/main/java/com/marketplace/service/CategoryService.java
  api/src/main/java/com/marketplace/service/impl/CategoryServiceImpl.java
  api/src/main/java/com/marketplace/utils/mapper/CategoryMapper.java
  api/src/main/resources/application.yml
  api/src/test/java/com/marketplace/controller/CategoryControllerTest.java
  api/src/test/java/com/marketplace/security/jwt/CustomAccessDeniedHandlerTest.java
  api/src/test/java/com/marketplace/service/impl/CategoryServiceImplTest.java
Labels: bug
